export const buttonsPortrait = [
  { text: 'C' },
  { text: 'Del' },
  { text: '%', isOperation: true },
  { text: '/', isOperation: true },
  { text: '7' },
  { text: '8' },
  { text: '9' },
  { text: '*', isOperation: true },
  { text: '4' },
  { text: '5' },
  { text: '6' },
  { text: '-', isOperation: true },
  { text: '1'},
  { text: '2'},
  { text: '3' },
  { text: '+', isOperation: true },
  { text: '', isOperation: true },
  { text: '0' },
  { text: '.', isOperation: true },
  { text: '=' },
];

export const buttonsLandscape = [
  { text: 'sin' },
  { text: 'cos' },
  { text: '%', isOperation: true },
  { text: 'C' },
  { text: 'Del' },
  { text: '+', isOperation: true },

  { text: 'tg' },
  { text: 'ctg' },
  { text: '7' },
  { text: '8' },
  { text: '9' },
  { text: '/', isOperation: true },

  { text: 'ln' },
  { text: 'sqrt' },
  { text: '4' },
  { text: '5' },
  { text: '6' },
  { text: '*', isOperation: true },

  { text: '!X', value: '!' },
  { text: '1/X', value: '1/', isOperation: true },
  { text: '1'},
  { text: '2'},
  { text: '3' },
  { text: '-', isOperation: true },

  { text: '(', isOperation: true },
  { text: ')', isOperation: true },
  { text: 'x^y', value: '^', isOperation: true },
  { text: '0' },
  { text: '.', isOperation: true },
  { text: '=' },
];